// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Printstream.Infrastructure;

#nullable disable

namespace Printstream.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110093517_Printstream")]
    partial class Printstream
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AddressPerson", b =>
                {
                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.HasKey("AddressID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("Person_Address", (string)null);
                });

            modelBuilder.Entity("EmailPerson", b =>
                {
                    b.Property<int>("EmailID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.HasKey("EmailID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("Person_Email", (string)null);
                });

            modelBuilder.Entity("PersonPhone", b =>
                {
                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneID")
                        .HasColumnType("integer");

                    b.HasKey("PersonID", "PhoneID");

                    b.HasIndex("PhoneID");

                    b.ToTable("Person_Phone", (string)null);
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(228)
                        .HasColumnType("character varying(228)");

                    b.HasKey("ID");

                    b.HasIndex("address")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Bunch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("bunch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.HasIndex("bunch")
                        .IsUnique();

                    b.ToTable("Bunch");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Bunch_History", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BunchID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BunchID");

                    b.HasIndex("PersonID");

                    b.ToTable("Bunch_History");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Email", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("character varying(52)");

                    b.HasKey("ID");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Email");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BunchID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonDataID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BunchID");

                    b.HasIndex("PersonDataID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.PersonData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.HasIndex("LastName", "FirstName", "MiddleName", "DateOfBirth", "IsMale")
                        .IsUnique();

                    b.ToTable("PersonData");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Phone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.HasIndex("phone")
                        .IsUnique();

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("AddressPerson", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmailPerson", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Email", null)
                        .WithMany()
                        .HasForeignKey("EmailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonPhone", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.Phone", null)
                        .WithMany()
                        .HasForeignKey("PhoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Bunch_History", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Bunch", "Bunch")
                        .WithMany()
                        .HasForeignKey("BunchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bunch");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Person", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Bunch", "Bunch")
                        .WithMany("Person")
                        .HasForeignKey("BunchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.PersonData", "PersonData")
                        .WithMany("Person")
                        .HasForeignKey("PersonDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bunch");

                    b.Navigation("PersonData");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Bunch", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.PersonData", b =>
                {
                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
