// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Printstream.Infrastructure;

#nullable disable

namespace Printstream.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AddressPerson", b =>
                {
                    b.Property<int>("AddressesID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.HasKey("AddressesID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("Person_Addresses", (string)null);
                });

            modelBuilder.Entity("EmailPerson", b =>
                {
                    b.Property<int>("EmailsID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.HasKey("EmailsID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("Person_Emails", (string)null);
                });

            modelBuilder.Entity("PersonPhone", b =>
                {
                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.Property<int>("PhonesID")
                        .HasColumnType("integer");

                    b.HasKey("PersonID", "PhonesID");

                    b.HasIndex("PhonesID");

                    b.ToTable("Person_Phones", (string)null);
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ResAddress")
                        .IsRequired()
                        .HasMaxLength(228)
                        .HasColumnType("character varying(228)");

                    b.HasKey("ID");

                    b.HasIndex("ResAddress")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Email", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("character varying(52)");

                    b.HasKey("ID");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.HasIndex("LastName", "FirstName", "MiddleName");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Printstream.Infrastructure.Configurations.Phone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Phones", (string)null);
                });

            modelBuilder.Entity("AddressPerson", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmailPerson", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Email", null)
                        .WithMany()
                        .HasForeignKey("EmailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonPhone", b =>
                {
                    b.HasOne("Printstream.Infrastructure.Configurations.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printstream.Infrastructure.Configurations.Phone", null)
                        .WithMany()
                        .HasForeignKey("PhonesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
